### ISSUE TITLE
aab build in aab v1.0.0-dev.2

### ISSUE THREAD

**Issue by RisingOrange** [glutanimate/anki-addon-builder#23]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
`aab ui` works well, the compiled resources work in Anki 2.1.50 Qt5 and Qt6. 
However when starting with an empty src/addon_name/gui folder and running `aab build` the contents of gui/resources are generated but the gui/forms only contains an empty qt5 folder. I also get this error:

```
=== Build task 1/1 ===

--- Building field-autocomplete 1.4.5 for local ---

Preparing source tree for field-autocomplete 1.4.5 ...
Cleaning repository...
Exporting Git archive...
Copying licenses...
Writing manifest...
Starting UI build tasks for target 'qt5'...
Qt resources folder found. Attempting to migrate...
Building files in 'designer' to 'src/field-autocomplete/gui/forms/qt5' with 'pyuic5'
Traceback (most recent call last):
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/bin/aab", line 8, in <module>
    sys.exit(main())
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/cli.py", line 310, in main
    args.func(args)
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/cli.py", line 92, in build
    builder.build(qt_versions=qt_versions, disttype=dist)
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/builder.py", line 89, in build
    self.build_dist(qt_versions=qt_versions, disttype=disttype, pyenv=pyenv)
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/builder.py", line 119, in build_dist
    ui_builder.build(qt_version=qt_version, pyenv=pyenv)
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/ui.py", line 153, in build
    self._build(
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/ui.py", line 232, in _build
    self._munge_form(out_file, resource_prefixes_to_replace)
  File "/home/jakubfidler/.virtualenvs/anki_21_50_beta9/lib/python3.9/site-packages/aab/ui.py", line 277, in _munge_form
    with path.open("r+", encoding="utf-8") as f:
  File "/usr/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jakubfidler/Documents/programming/anki_addons/anki-field-autocomplete/build/dist/src/field-autocomplete/gui/forms/qt5/settings_dialog.py'
```

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of aab
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your set-up

Please run `aab -h` and paste the output below:

```
Anki Add-on Builder v1.0.0-dev.2

Copyright (C) 2016-2022  Aristotelis P. (Glutanimate)  <https://glutanimate.com>

This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions; For details please see the LICENSE file.

usage: aab [-h] [-v] {build,ui,manifest,clean,create_dist,build_dist,package_dist} ...

positional arguments:
  {build,ui,manifest,clean,create_dist,build_dist,package_dist}
    build               Build and package add-on for distribution
    ui                  Compile add-on user interface files
    manifest            Generate manifest file from add-on properties in addon.json
    clean               Clean leftover build files
    create_dist         Prepare source tree distribution for building under build/dist. This is intended to be used in build scripts and should be run before `build_dist` and `package_dist`.
    build_dist          Build add-on files from prepared source tree under build/dist. This step performs all source code post-processing handled by aab itself (e.g. building the Qt UI and
                        writing the add-on manifest). As with `create_dist` and `package_dist`, this command is meant to be used in build scripts where it can provide an avenue for performing
                        additional processing ahead of packaging the add-on.
    package_dist        Package pre-built distribution of add-on files under build/dist into a distributable .ankiaddon package. This is inteded to be used in build scripts and called after
                        both `create_dist` and `build_dist` have been run.

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Enable verbose output
```

*Please fill in details about your operating system and environment:*

- OS: Linux pop-os 5.16.11-76051611-generic
- Python version: 3.9.7
- Anki version: 2.1.50 beta 9

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by ascension4humanity** [comment]
same error here. work-around?

**Comment by RisingOrange** [comment]
Currently I just run `aab ui` and then manually put the license into the directory, delete the \_\_pycache\_\_ directories and compress the files. (Maybe I forgot some steps.)

**Comment by sos0** [comment]
Can someone elaborate a bit more on the workaround here? I'm unable to get my ui files to build (forms not seen in build directory).

```python
### Assume some_options.ui is in the /design directory, where the widget class is called QDialog:
from .forms import some_options

class SomeOptions(QDialog):
    def __init__(self, mw):
        super(SomeOptions, self).__init__(parent=mw)
        
        # Try to load qt-designer form:
        self.f = some_options.Ui_Dialog()
```

Error:
`ModuleNotFoundError: No module named 'projectname.gui.forms'`
